name: Lint locales

on:
  push:
    branches:
      - taiyme
    paths:
      - .github/workflows/lint-locales.yaml
      - locales/**/*
  pull_request:
    paths:
      - .github/workflows/lint-locales.yaml
      - locales/**/*

jobs:
  check_verify:
    name: Check verify
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Enable corepack
        run: |
          corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm i --frozen-lockfile

      - name: Check Verify
        working-directory: locales
        run: |
          node verify.js

  check_dts:
    name: Check locale type
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Enable corepack
        run: |
          corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm i --frozen-lockfile

      - name: Generate locale type
        run: |
          node --input-type=module \
            --eval 'import generateDTS from "./locales/generateDTS.js"; generateDTS();'

      - name: Check locale type changes
        id: check-changes
        run: |
          if git diff --name-only HEAD | grep -x locales/index.d.ts; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Comment PR (upsert)
        if: github.event_name == 'pull_request' && steps.check-changes.outputs.changes == 'true'
        uses: thollander/actions-comment-pull-request@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment_tag: check-locale-type
          mode: upsert
          create_if_not_exists: true
          message: |
            Please regenerate locale type definitions! :pray:
            locale型定義の再生成をお願いします！ :pray:

            ```sh
            pnpm run build-assets
            ```

      - name: Comment PR (delete)
        if: github.event_name == 'pull_request' && steps.check-changes.outputs.changes == 'false'
        uses: thollander/actions-comment-pull-request@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment_tag: check-locale-type
          mode: delete
          create_if_not_exists: false
          message: |
            Thank you!

      - name: Make failure if changes are detected
        if: steps.check-changes.outputs.changes == 'true'
        run: exit 1
