name: Release

on:
  workflow_dispatch:
    inputs:
      base_version:
        type: string
        description: Enter base version. (e.g. 2024.8.0)
        required: true
        default: ""

env:
  repository: taiyme/misskey
  develop_branch: taiyme
  release_branch: release

jobs:
  check_context:
    name: Check context
    runs-on: ubuntu-22.04
    steps:
      - name: Check actor
        if: github.actor != github.repository_owner
        run: exit 1

      - name: Check branch
        if: github.ref_name != env.develop_branch
        run: exit 1

      - name: Check repository
        if: github.repository != env.repository
        run: exit 1

      - name: Check base version
        run: |
          base="${{ inputs.base_version }}"
          if [ -z "$base" ]; then
            exit 1
          fi

          year="$(echo "$base" | cut -d. -f1)"
          if [[ ! "$year" =~ ^[0-9]+$ ]]; then
            exit 1
          fi

          month="$(echo "$base" | cut -d. -f2)"
          if [[ "$month" -lt 1 && "$month" -gt 12 ]]; then
            exit 1
          fi

          patch="$(echo "$base" | cut -d. -f3)"
          if [[ ! "$patch" =~ ^[0-9]+$ ]]; then
            exit 1
          fi

  parse_version:
    name: Parse new version
    runs-on: ubuntu-22.04
    needs:
      - check_context
    outputs:
      NEW_VERSION: ${{ steps.generate.outputs.NEW_VERSION }}
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          fetch-depth: 1

      - name: Generate new version
        id: generate
        run: |
          current_version="$(cat package.json | jq -r '.version')"
          current_base="$(echo $current_version | sed 's/-.*//')"
          new_base="${{ inputs.base_version }}"
          new_base="${new_base:-$current_base}"
          new_suffix=""
          if [[ "$current_version" != "$current_base" && "$current_base" == "$new_base" ]]; then
            new_suffix="$(($(echo $current_version | cut -d- -f2 | cut -d. -f2) + 1))"
          fi
          new_suffix="${new_suffix:-"0"}"
          new_version="${new_base}-taiyme.${new_suffix}"
          echo "NEW_VERSION=${new_version}" >> $GITHUB_OUTPUT

  bump_version_update:
    name: Bump version (update)
    runs-on: ubuntu-22.04
    needs:
      - parse_version
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          fetch-depth: 1

      - name: Update package.json (root)
        run: |
          jq --tab '.version = "${{ needs.parse_version.outputs.NEW_VERSION }}"' package.json > tmp
          mv tmp package.json

      - name: Update package.json (misskey-js)
        working-directory: packages/misskey-js
        run: |
          jq --tab '.version = "${{ needs.parse_version.outputs.NEW_VERSION }}"' package.json > tmp
          mv tmp package.json

      - name: Update compose_example.yml
        run: |
          old_docker_image="$(yq '.services.web.image' compose_example.yml)"
          new_docker_image='ghcr.io/${{ env.repository }}:${{ needs.parse_version.outputs.NEW_VERSION }}'
          sed -i "s|image: ${old_docker_image}|image: ${new_docker_image}|g" compose_example.yml

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bump_version_files
          path: |
            package.json
            packages/misskey-js/package.json
            compose_example.yml

  bump_version_upload:
    name: Bump version (upload)
    runs-on: ubuntu-22.04
    needs:
      - parse_version
      - bump_version_update
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_SECRET }}

      - name: Checkout ${{ env.develop_branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ env.develop_branch }}
          fetch-depth: 1
          token: ${{ steps.app-token.outputs.token }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bump_version_files

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}
          git add .
          git commit -m "Release: ${{ needs.parse_version.outputs.NEW_VERSION }}"
          git tag ${{ needs.parse_version.outputs.NEW_VERSION }}
          git push origin HEAD
          git push origin ${{ needs.parse_version.outputs.NEW_VERSION }}

  create_pr:
    name: Create PR
    runs-on: ubuntu-22.04
    needs:
      - parse_version
      - bump_version_upload
    outputs:
      PR_NUMBER: ${{ steps.create_pr.outputs.CREATED_PR }}
    permissions:
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_SECRET }}

      - name: Checkout ${{ env.develop_branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ env.develop_branch }}
          fetch-depth: 0

      - name: Create PR
        id: create_pr
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          created_pr="$(gh pr create --draft --base ${{ env.release_branch }} --head ${{ env.develop_branch }} --title "Release: ${{ needs.parse_version.outputs.NEW_VERSION }}" --body "")"
          created_pr="$(echo $created_pr | awk -F '/' '/\/pull\/[0-9]+$/ {print $NF}')"
          echo "CREATED_PR=${created_pr}" >> $GITHUB_OUTPUT

  publish_docker_image:
    name: Publish Docker image
    needs:
      - parse_version
      - bump_version_upload
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/docker-publish.yaml
    with:
      tags: |
        ${{ needs.parse_version.outputs.NEW_VERSION }}
        latest

  merge_pr:
    name: Merge PR
    runs-on: ubuntu-22.04
    needs:
      - create_pr
      - publish_docker_image
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_SECRET }}

      - name: Checkout ${{ env.develop_branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ env.develop_branch }}
          fetch-depth: 1

      - name: Merge PR
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh pr ready ${{ needs.create_pr.outputs.PR_NUMBER }}
          gh pr merge ${{ needs.create_pr.outputs.PR_NUMBER }} --merge --auto

  release:
    name: Release
    runs-on: ubuntu-22.04
    needs:
      - parse_version
      - merge_pr
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_SECRET }}

      - name: Checkout ${{ env.release_branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ env.release_branch }}
          fetch-depth: 0

      - name: Create Release
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh release create ${{ needs.parse_version.outputs.NEW_VERSION }} --generate-notes
